### ISSUE TITLE
Russian translation and missing string

### ISSUE THREAD

**Issue by aerohub** [aduth/dones#19]
Hello! Thank you for sharing this theme, it's great.

I have translated the theme into Russian, you'll find it [here](https://poeditor.com/projects/po_edit?id_language=134&id=151513). 

Doing this I realized that there is no localization string for DELETE button. Will you add it?

![1](https://user-images.githubusercontent.com/16353578/35278112-0ae98e2a-005a-11e8-986f-06675025aba3.png)

**Comment by aduth** [comment]
Thanks so much for taking the time to localize the plugin!

I can definitely plan to fix the issue with the "Delete" string being absent. Will hopefully have some availability in the next week to take a look.

**Comment by aduth** [comment]
Sorry for the delay. This is now fixed by 9592c58, and I've updated the project on POEditor to include the new term.

I'll spend some time improving the theme build script so that we can pull in your localization from POEditor, and include it in the next release.

Thanks again!

**Comment by aduth** [comment]
Added language file download build step in d3c4b7453fb85fa73454963ff0c615df7df73a7a, meaning your translation should be made available in the next release.

**Comment by aerohub** [comment]
Hello,

now I am sorry for the delay. The delete string is translated.

Thank you!
